apiVersion: v1
kind: Service
metadata:
  labels:
    app: django
  name: django
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: django
status:
  loadBalancer: {}
