apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        name: nginx
        ports:
        - containerPort: 80
          hostIP: 0.0.0.0
        - containerPort: 443
          hostIP: 0.0.0.0
        resources: {}
        volumeMounts:
        - mountPath: /etc/letsencrypt
          name: nginx-claim0
        - mountPath: /var/lib/letsencrypt
          name: nginx-claim1
      restartPolicy: Always
      volumes:
      - name: nginx-claim0
        persistentVolumeClaim:
          claimName: nginx-claim0
      - name: nginx-claim1
        persistentVolumeClaim:
          claimName: nginx-claim1
status: {}
